<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BackgroundCut.Desktop</AssemblyName>
    <RootNamespace>BackgroundCut.Desktop</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>..\..\assets\BackgroundCut.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BackgroundCut.Application\BackgroundCut.Application.csproj" />
    <ProjectReference Include="..\BackgroundCut.Infrastructure\BackgroundCut.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="..\..\assets\BackgroundCut.ico" Link="BackgroundCut.ico" />
  </ItemGroup>
</Project>
