<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DryCut.Desktop</AssemblyName>
    <RootNamespace>DryCut.Desktop</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon>..\..\assets\DryCut.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DryCut.Application\DryCut.Application.csproj" />
    <ProjectReference Include="..\DryCut.Infrastructure\DryCut.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.20" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.20" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.20" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.20" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.20" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="..\..\assets\DryCut.ico" Link="Assets\DryCut.ico" />
  </ItemGroup>
</Project>
