[CmdletBinding()]
param(
    [string]$Output = (Join-Path $PSScriptRoot '..\installer\staging\THIRD-PARTY-NOTICES.txt'),
    [string]$Project = (Join-Path $PSScriptRoot '..\src\BackgroundCut.Desktop\BackgroundCut.Desktop.csproj'),
    [switch]$DryRun
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$out = [IO.Path]::GetFullPath($Output)
if ($DryRun) { Write-Host "DRY RUN: would collect package metadata and license files into $out"; exit 0 }
New-Item -ItemType Directory -Force -Path ([IO.Path]::GetDirectoryName($out)) | Out-Null
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('BackgroundCut third-party notices')
$lines.Add('Generated by scripts/assemble-notices.ps1; do not edit.')
$lines.Add('')
$lines.Add('BackgroundCut default model')
$lines.Add('IS-Net general-use q8 ONNX - Apache License 2.0')
$lines.Add('Source: https://huggingface.co/SacredNoir/isnet-general-use-onnx')
$lines.Add('')
$lines.Add('Application dependencies')
$json = & dotnet list $Project package --include-transitive --format json 2>$null
if ($LASTEXITCODE -eq 0 -and $json) {
    try {
        $data = $json | ConvertFrom-Json
        foreach ($p in @($data.projects[0].frameworks | ForEach-Object { $_.topLevelPackages; $_.transitivePackages } | Where-Object { $_ })) {
            $lines.Add(('- {0} {1}' -f $p.id, $p.resolvedVersion))
        }
    } catch { $lines.Add('- Package metadata could not be parsed; inspect the publish output.') }
} else { $lines.Add('- No package metadata available (project restore may be required).') }
$lines.Add('')
$lines.Add('License texts shipped by dependencies are included below when present in the NuGet cache.')
$lines.Add('')
$seen = @{}
$patterns = @('LICENSE*','NOTICE*','COPYING*')
$roots = @((Join-Path $env:USERPROFILE '.nuget\packages'), (Join-Path $env:ProgramFiles 'dotnet\packs'))
foreach ($root in $roots) {
    if (Test-Path $root) {
        foreach ($pattern in $patterns) {
            Get-ChildItem -LiteralPath $root -Filter $pattern -File -Recurse -ErrorAction SilentlyContinue | Sort-Object FullName | ForEach-Object {
                $key = $_.FullName.ToLowerInvariant()
                if (-not $seen.ContainsKey($key)) { $seen[$key] = $true; $lines.Add("===== $($_.Name) ====="); $lines.Add((Get-Content -Raw -LiteralPath $_.FullName)); $lines.Add('') }
            }
        }
    }
}
[IO.File]::WriteAllLines($out, $lines, [Text.UTF8Encoding]::new($false))
Write-Host "Wrote notices: $out"
