[CmdletBinding()]
param(
    [string]$Output = (Join-Path $PSScriptRoot '..\installer\staging\THIRD-PARTY-NOTICES.txt'),
    [string]$Project = (Join-Path $PSScriptRoot '..\src\BackgroundCut.Desktop\BackgroundCut.Desktop.csproj'),
    [switch]$DryRun
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$out = [IO.Path]::GetFullPath($Output)
if ($DryRun) { Write-Host "DRY RUN: would collect package metadata and license notices into $out"; exit 0 }
New-Item -ItemType Directory -Force -Path ([IO.Path]::GetDirectoryName($out)) | Out-Null

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('BackgroundCut third-party notices')
$lines.Add('Generated by scripts/assemble-notices.ps1.')
$lines.Add('')
$lines.Add((Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot '..\licenses\MODEL-NOTICES.txt')))
$lines.Add('')
$lines.Add('Application dependencies')
$lines.Add('------------------------')

$json = & dotnet list $Project package --include-transitive --format json 2>$null
if ($LASTEXITCODE -ne 0 -or -not $json) { throw 'Could not collect NuGet package metadata.' }
$data = $json | ConvertFrom-Json
$packages = @{}
foreach ($framework in @($data.projects[0].frameworks)) {
    $frameworkPackages = @()
    if ($framework.PSObject.Properties.Name -contains 'topLevelPackages') { $frameworkPackages += @($framework.topLevelPackages) }
    if ($framework.PSObject.Properties.Name -contains 'transitivePackages') { $frameworkPackages += @($framework.transitivePackages) }
    foreach ($package in $frameworkPackages) {
        if ($package -and $package.id -and $package.resolvedVersion) {
            $packages[$package.id.ToLowerInvariant()] = $package
        }
    }
}

foreach ($key in ($packages.Keys | Sort-Object)) {
    $package = $packages[$key]
    $packageRoot = Join-Path (Join-Path (Join-Path $env:USERPROFILE '.nuget\packages') $key) $package.resolvedVersion
    $nuspec = Get-ChildItem -LiteralPath $packageRoot -Filter '*.nuspec' -File -ErrorAction SilentlyContinue | Select-Object -First 1
    $license = 'See package metadata.'
    $licenseUrl = $null
    $projectUrl = $null
    if ($nuspec) {
        [xml]$metadata = Get-Content -Raw -LiteralPath $nuspec.FullName
        $licenseNode = $metadata.SelectSingleNode("//*[local-name()='metadata']/*[local-name()='license']")
        $licenseUrlNode = $metadata.SelectSingleNode("//*[local-name()='metadata']/*[local-name()='licenseUrl']")
        $projectUrlNode = $metadata.SelectSingleNode("//*[local-name()='metadata']/*[local-name()='projectUrl']")
        if ($licenseNode) {
            if ($licenseNode.type -eq 'file') {
                $licensePath = Join-Path $packageRoot $licenseNode.InnerText
                $license = if (Test-Path -LiteralPath $licensePath) { "File: $($licenseNode.InnerText) (content included below)" } else { "File: $($licenseNode.InnerText)" }
            } else { $license = "Expression: $($licenseNode.InnerText)" }
        }
        if ($licenseUrlNode) { $licenseUrl = $licenseUrlNode.InnerText }
        if ($projectUrlNode) { $projectUrl = $projectUrlNode.InnerText }
    }
    $lines.Add("$($package.id) $($package.resolvedVersion)")
    $lines.Add("License: $license")
    if ($licenseUrl) { $lines.Add("License URL: $licenseUrl") }
    if ($projectUrl) { $lines.Add("Project: $projectUrl") }
    if ($licenseNode -and $licenseNode.type -eq 'file' -and (Test-Path -LiteralPath $licensePath)) {
        $lines.Add('')
        $lines.Add((Get-Content -Raw -LiteralPath $licensePath))
    }
    $lines.Add('')
}

[IO.File]::WriteAllLines($out, $lines, [Text.UTF8Encoding]::new($false))
Write-Host "Wrote notices: $out"
